
### Get Product 
GET http://localhost:8081/api/v2/product HTTP/1.1


### Get Product with Token
GET http://localhost:8081/api/v2/product HTTP/1.1
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWI2NTU1NjE4ZGUwMmE0ZGFiZjFlNCIsImxldmVsIjoibm9ybWFsIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYwNTA2ODkwNiwiZXhwIjoxNjA1MDY5OTA2LCJhdWQiOiJodHRwOi8vY29kZW1vYmlsZXMuY29tIiwiaXNzIjoiQ29kZU1vYmlsZXMgTHRkIiwic3ViIjoiY2hhaXlhc2l0LnRAZ21haWwuY29tIn0.rg3hnPfMufaibN0zB5Trqi5N_W8AX4xrA_PutxhBE_kiw-9Mkb29RpPomSJauKKtQrvp1oQavzwzDxvo7y7yXHSzz55USLIg64bbU4WGUraNcqjESRnvIm7Gu8ZDrpAx-AlB7h1mjvBh3vIbLfEby_Gzvxg3cjNhsnqvWkg80xk

### Get Product with keyword
GET http://localhost:8081/api/v2/product/name/WeMos HTTP/1.1


### Get Product by ID 
GET http://localhost:8081/api/v2/product/id/44 HTTP/1.1


### Delete Product by ID 
DELETE  http://localhost:8081/api/v2/product/id/44 HTTP/1.1



### Create 
POST http://localhost:8081/api/v2/product HTTP/1.1
x-access-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWI2NTU1NjE4ZGUwMmE0ZGFiZjFlNCIsImxldmVsIjoibm9ybWFsIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYwNTA2ODkwNiwiZXhwIjoxNjA1MDY5OTA2LCJhdWQiOiJodHRwOi8vY29kZW1vYmlsZXMuY29tIiwiaXNzIjoiQ29kZU1vYmlsZXMgTHRkIiwic3ViIjoiY2hhaXlhc2l0LnRAZ21haWwuY29tIn0.rg3hnPfMufaibN0zB5Trqi5N_W8AX4xrA_PutxhBE_kiw-9Mkb29RpPomSJauKKtQrvp1oQavzwzDxvo7y7yXHSzz55USLIg64bbU4WGUraNcqjESRnvIm7Gu8ZDrpAx-AlB7h1mjvBh3vIbLfEby_Gzvxg3cjNhsnqvWkg80xk
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Angular 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

300
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

180
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Edit 
PUT http://localhost:8081/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTk4OTg1OTQsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.e8ZcnQFnye_DldUnzyqfth37SVB0hp8ZEjvRCy7th4s
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="product_id";

44
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Arduino board (Edit)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

101
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

200
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test_2nd.jpg"
Content-Type: image/png

< ./test_2nd.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--



---------------------------------------------
### Heroku

### Create 
POST https://cmgostock.herokuapp.com/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDExNzI5NTgsImlkIjo0LCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiY20yIn0.Gjh80yfcwzR8nTtiD4tM0zTDb9CgemuGGJoLB5v0DF8
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Angular2 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

300
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

180
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--